## Numpy Basics

In [2]:
import numpy as np

### Creating array from list

In [ ]:
array_1D = np.array([1,2,3,4,5])
print("1D array :", array_1D)

array_2d = np.array([[1,2,3],[4,5,6]])
print("2D array :", array_2d)

1D array : [1 2 3 4 5]
2D array : [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [ ]:
np_list = [1,2,3]
print("Python list multiplication :",np_list*2)

np_array = np.array([4,5,6])
print("Python array Multiplication :" , np_array * 2) # Element wide Multiplication

Python list multiplication : [1, 2, 3, 1, 2, 3]
Python array Multiplication : [ 8 10 12]


In [ ]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time :" , time.time()-start)

start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy operation time :" , time.time()-start)




 List operation time : 0.05044078826904297

 Numpy operation time : 0.0013930797576904297


### Creating Array from Scratch

In [ ]:
import numpy as np

zeros = np.zeros((3,4)) # 3 is the row and 4 is the column
print("Zeros array : \n",zeros)

ones = np.ones((2,3)) # 2 is the row and 3 is the column 
print("Ones array is :\n",ones)

full = np.full((2,2),7) # array with 2 row and 2 column all emenents are 7
print("Full array is : \n",full)

random = np.random.random((2,3)) # 2 rows and 3 column
print("Random array is :\n",random)

sequence = np.arange(0,10,2) # start, stop-1 ,step
print("Sequence array is : \n",sequence)

Zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array is :
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array is : 
 [[7 7]
 [7 7]]
Random array is :
 [[0.01343345 0.5385011  0.08236775]
 [0.60289772 0.27212946 0.14958997]]
Sequence array is : 
 [0 2 4 6 8]


### Vector , Matrix and Tensor

In [13]:
vector = np.array([1,2,3])
print("Vector is : ",vector)

matrix = np.array([[4,5,6],
                  [7,8,9]])
print("Matrix is :\n ",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor :\n",tensor)


Vector is :  [1 2 3]
Matrix is :
  [[4 5 6]
 [7 8 9]]
Tensor :
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [15]:
array = np.array([[1,2,3],
                  [4,5,6]])
print("Shape :",array.shape)
print("Dimention :",array.ndim)
print("Size :",array.size)
print("Datatype :",array.dtype)

Shape : (2, 3)
Dimention : 2
Size : 6
Datatype : int64


### Array Reshaping

In [ ]:
import numpy as np

arr = np.arange(12)
print("Original Array :",arr)

reshaped = arr.reshape((3,4)) # 3 row and 4 column
print("\n Reshaped array :\n",reshaped)

flattened = reshaped.flatten() # Arrange all the elements in a single line 
print("\n Flattened array :",flattened)

# ravel (returns view insted of copy)
ravel = flattened.ravel()
print("\n Ravel array :", ravel)

# Transpose
transpose = reshaped.T     # The dot T is a fnction to make the matrix transpose
print("Transpose matrix :\n",transpose)

Original Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Ravel array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose matrix :
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
