## Numpy Array Operations

### Numpy Array Indexing

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("With slicing :",arr[2:8]) # from 2nd index to (n-1) = 7 index
print("\n With Step :",arr[2:8:2]) # START(2)  STOP(7)  STEP(2)
print("\n Negetive inxexing :",arr[-3]) # prints the 3rd element from last

With slicing : [3 4 5 6 7 8]

 With Step : [3 5 7]

 Negetive inxexing : 7


In [ ]:
array_2d = np.array([[1,2,3], # 0 th Row
                     [4,5,6], # 1 st Row
                     [7,8,9]])# 2 nd Row

print("Specific Element :",array_2d[1,2]) # 1st row 2nd element
print("Entire Row :", array_2d[1]) # print the entire 1st row
print("Entire column :", array_2d[:, 2]) # Print the entite 2nd column

Specific Element : 6
Entire Row : [4 5 6]
Entire column : [3 6 9]


### Sorting

In [1]:
import numpy as np

unsorted = np.array([4,5,2,4,8,9,1])
print("Sorted Array :", np.sort(unsorted))

Sorted Array : [1 2 4 4 5 8 9]


In [13]:
unsorted_2D_array = np.array([[3,1],[1,2],[2,3]])
print("Sorted array by column : \n",np.sort(unsorted_2D_array,axis=0)) # sort the array top to bottom
print("Sorted array by row : \n",np.sort(unsorted_2D_array,axis=1)) # sort the array left to right

Sorted array by column : 
 [[1 1]
 [2 2]
 [3 3]]
Sorted array by row : 
 [[1 3]
 [1 2]
 [2 3]]


### Filtering the array

In [10]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = number[number % 2 == 0]
print("Even numbers :",even_numbers)

Even numbers : [ 2  4  6  8 10]


### Filter with mask

In [12]:
mask = number > 5
print("Numbers greater than 5 :",number[mask])

Numbers greater than 5 : [ 6  7  8  9 10]


### Fancy Indexing vs np.where

In [17]:
index = [0,2,4] # index of 0th , 2nd and 4th position
print(number[index]) # print 1,3,5 because in number parameter we have assigned those values

where_result = np.where(number > 5)
print(where_result)
print("NP where :",number[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where : [ 6  7  8  9 10]


In [24]:
condition_array = np.where(number > 5 , number*5 , number)
print(condition_array)



[ 1  2  3  4  5 30 35 40 45 50]


### Adding and Removing Data

In [ ]:
# Merging the Two array
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# combined = arr1 + arr2 # this will add the elements of the array
# print(combined)

combined = np.concatenate((arr1 , arr2)) # concatenate method use to merge the two array
print(combined) 

[1 2 3 4 5 6]


### Array compatibility

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("same size ? :", a.shape == b.shape ) # if the shape is same then output will be true either false

same size ? : True


In [ ]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

print("Original Array : \n",original,"\n")
with_new_row = np.vstack((original,new_row))
print("with new row : \n",with_new_row,"\n")

new_column = np.array([[7],[8],[9]])
print("With new column : \n",np.hstack((with_new_row,new_column)))



Original Array : 
 [[1 2]
 [3 4]] 

with new row : 
 [[1 2]
 [3 4]
 [5 6]] 

With new column : 
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],
               [3,4,5,6]])
print("The array is : \n",arr)


The array is : 
 [[1 2 3 4]
 [3 4 5 6]]
