# Practice Numpy for Better Understanding

In [ ]:
import numpy as np

In [8]:
# ## Create an array containing the numbers from 1 to 10.
import numpy as np
arr = np.arange(0,11)
print("Array elements :",arr)

Array elements : [ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Find Shape, Dimensions and Total Elements
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape of the array :",arr.shape) # (2,3) means 2 row 3 columns
print("Dimension of the array :",arr.ndim) # dimensions of the array is 2
print("Total elements are ;",arr.size) # total elements are 6

Shape of the array : (2, 3)
Dimension of the array : 2
Total elements are ; 6


In [ ]:
# Reshape the array
import numpy as np

arr = np.arange(12)
print("Reshaped array :\n",arr.reshape(3,4))

REshaped array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
# 4. Sort an Array
import numpy as np
arr = np.array([1,4,6,7,5,2,3,9,8])
print("Sorted array : ",np.sort(arr))

Sorted array :  [1 2 3 4 5 6 7 8 9]
